#cloud-config
groups: []
users: []
#  - name: jelle
#    gecos: Jelle Herold
#    primary-group: wheel
#    sudo: ALL=(ALL) NOPASSWD:ALL
#    no-user-group: true
#    ssh-authorized-keys:
#      - ssh-rsa AAAAB3NzYOURPUBKEYCONTENTSHERE user@host